services:
  influx:
    image: influxdb:2
    volumes:
      - ./deploymentData/influx/data:/var/lib/influxdb2
      - ./deploymentData/influx/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=polar_reflow
      - DOCKER_INFLUXDB_INIT_PASSWORD=polar_reflow
      - DOCKER_INFLUXDB_INIT_ORG=polar_reflow
      - DOCKER_INFLUXDB_INIT_BUCKET=hrv
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sdwefrejktkyukytjrjtrw
#
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: "1000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin2
    volumes:
      - ./deploymentData/grafana/data:/var/lib/grafana
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./provisioning/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./provisioning/grafana/dashboards/hrv.json:/var/lib/grafana/dashboards/hrv.json

#  polar_reflow:
#    build: ../
#    ports:
#      - "6969:6969"
#    environment:
#      - POLAR_REFLOW_SERVE=true
#      - POLAR_REFLOW_TOKEN=sdwefrejktkyukytjrjtrw
#      - POLAR_REFLOW_ORG=polar_reflow
#      - POLAR_REFLOW_BUCKET=hrv
#    depends_on:
#      - influx


#  mongodb:
#    image: mongodb/mongodb-community-server:7.0.3-ubuntu2204
#    restart: always
#    user: "1000"
#    ports:
#      - 27017:27017
#    environment:
#      MONGODB_INITDB_ROOT_USERNAME: polar_reflow
#      MONGODB_INITDB_ROOT_PASSWORD: polar_reflow
#    volumes:
#      - ./deploymentData/mongo/data:/data/db
